# Generated by Django 3.0 on 2022-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220905_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
    ]
