export const FETCH_ALL_POSTS_START = "FETCH_ALL_POSTS_START";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POST_FAIL = "FETCH_ALL_POST_FAIL";

export const FETCH_DETAIL_POST_START = "FETCH_DETAIL_POST_START";
export const FETCH_DETAIL_POST_SUCCESS = "FETCH_DETAIL_POST_SUCCESS";
export const FETCH_DETAIL_POST_FAIL = "FETCH_DETAIL_POST_FAIL";

export const FETCH_POSTS_BY_CATEGORY_START = "FETCH_POSTS_BY_CATEGORY";
export const FETCH_POSTS_BY_CATEGORY_SUCCESS =
    "FETCH_POSTS_BY_CATEGORY_SUCCESS";
export const FETCH_POSTS_BY_CATEGORY_FAIL = "FETCH_POSTS_BY_CATEGORY_FAIL";


export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT = "LOGOUT"
export const ACTIVATE_USER = "ACTIVATE_USER"


export const CREATE_COMMENT_START = "LOGIN_USER_START";
export const CREATE_COMMENT_SUCCESS = "LOGIN_USER_SUCCESS";
export const CREATE_COMMENT_FAIL = "LOGIN_USER_FAIL";


export const SHARE_CURRENT_USER = "SHARE_CURRENT_USER";
