# Generated by Django 3.0 on 2022-09-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, default='sample.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
