# Generated by Django 3.0 on 2022-09-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220906_1051'),
        ('posts', '0002_auto_20220906_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_category', to='category.Category'),
        ),
    ]
