# Generated by Django 3.0 on 2022-09-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230106_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=models.ImageField(blank=True, default='sample.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, default='sample.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, default='sample.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='posts.Post'),
        ),
    ]
