# Generated by Django 3.2.7 on 2023-02-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230130_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/webmonc/image/upload/v1658887052/portfolio/book-store/default_img_hfhgpg.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/webmonc/image/upload/v1658887052/portfolio/book-store/default_img_hfhgpg.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo3',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/webmonc/image/upload/v1658887052/portfolio/book-store/default_img_hfhgpg.jpg', max_length=400),
        ),
    ]
